import { Restaurant, MealItem, WhoopData } from './types'

export const restaurants: Restaurant[] = [
  {
    id: 'reflect',
    name: 'Reflect',
    logoUrl: '/reflect-restaurant-logo.jpg',
    description: 'Healthy meals with full macro tracking',
    address: 'Al Gharrafa, Qatar',
    cuisine: ['Healthy', 'Mediterranean', 'International'],
    rating: 4.7,
    priceRange: '$$',
    isPartner: true
  },
  {
    id: 'oz-pure',
    name: 'Oz Pure',
    logoUrl: '/oz-pure-restaurant-logo.jpg',
    description: 'Pure and nutritious meal options',
    address: 'Umm Salal Mohammed, Qatar',
    cuisine: ['Healthy', 'International'],
    rating: 4.6,
    priceRange: '$$',
    isPartner: true
  },
  {
    id: 'diet-shop',
    name: 'Diet Shop By Diet Center',
    logoUrl: '/diet-shop-logo.jpg',
    description: 'Specialized diet meals and nutrition',
    address: 'Al Kharaitiyat, Qatar',
    cuisine: ['Healthy', 'International'],
    rating: 4.5,
    priceRange: '$$',
    isPartner: true
  },
  {
    id: 'diet-market',
    name: 'Diet Market',
    logoUrl: '/diet-market-logo.jpg',
    description: 'Fresh and healthy market selections',
    address: 'Al Gharrafa, Qatar',
    cuisine: ['Healthy', 'International'],
    rating: 4.6,
    priceRange: '$$',
    isPartner: true
  },
  {
    id: 'love-diet-food',
    name: 'Love Diet Food',
    logoUrl: '/love-diet-food-logo.jpg',
    description: 'Nutritious meals made with love',
    address: 'Lusail, Qatar',
    cuisine: ['Healthy', 'International'],
    rating: 4.5,
    priceRange: '$$',
    isPartner: true
  },
  {
    id: 'anabolic-to-go',
    name: 'Anabolic To Go',
    logoUrl: '/anabolic-to-go-logo.jpg',
    description: 'High-protein fitness meals on the go',
    address: 'Legtaifiya - West Bay Lagoon, Qatar',
    cuisine: ['Healthy', 'High-Protein'],
    rating: 4.7,
    priceRange: '$$',
    isPartner: true
  },
  {
    id: 'diet-cafe',
    name: 'Diet Cafe',
    logoUrl: '/diet-cafe-logo.jpg',
    description: 'Healthy cafe with diverse menu',
    address: 'Al Gharrafa, Qatar',
    cuisine: ['Healthy', 'Cafe', 'International'],
    rating: 4.6,
    priceRange: '$$',
    isPartner: true
  },
  {
    id: 'lean-n-fit',
    name: 'Lean N Fit Restaurant',
    logoUrl: '/lean-n-fit-logo.jpg',
    description: 'Fitness-focused nutrition meals',
    address: 'Al Duhail, Qatar',
    cuisine: ['Healthy', 'International'],
    rating: 4.8,
    priceRange: '$$',
    isPartner: true
  },
  {
    id: 'ivy-diet',
    name: 'Ivy Diet Healthy Foods',
    logoUrl: '/ivy-diet-logo.jpg',
    description: 'Healthy and balanced meal options',
    address: 'Lusail, Qatar',
    cuisine: ['Healthy', 'International'],
    rating: 4.6,
    priceRange: '$$',
    isPartner: true
  },
  {
    id: 'crave',
    name: 'Crave',
    logoUrl: '/crave-restaurant-logo.jpg',
    description: 'Satisfying healthy cravings',
    address: 'Al Daayen, Qatar',
    cuisine: ['Healthy', 'International'],
    rating: 4.7,
    priceRange: '$$',
    isPartner: true
  },
  {
    id: 'xdiet',
    name: 'XDiet Restaurant',
    logoUrl: '/xdiet-logo.jpg',
    description: 'Expert diet meal planning',
    address: 'Umm Salal, Qatar',
    cuisine: ['Healthy', 'International'],
    rating: 4.5,
    priceRange: '$$',
    isPartner: true
  },
  {
    id: 'al-mosak',
    name: 'Al Mosak',
    logoUrl: '/al-mosak-logo.jpg',
    description: 'Traditional healthy cuisine',
    address: 'Umm Salal Mohammed, Qatar',
    cuisine: ['Healthy', 'Middle Eastern', 'International'],
    rating: 4.6,
    priceRange: '$$',
    isPartner: true
  },
  {
    id: 'diet-house',
    name: 'Diet House',
    logoUrl: '/diet-house-logo.jpg',
    description: 'Your healthy eating destination',
    address: 'Umm Salal Mohammed, Qatar',
    cuisine: ['Healthy', 'International'],
    rating: 4.7,
    priceRange: '$$',
    isPartner: true
  }
]

export const meals: MealItem[] = [
  // Reflect meals
  {
    id: 'reflect-pepper-chicken',
    name: 'Pepper Chicken',
    description: 'Grilled chicken with black pepper seasoning',
    imageUrl: '/grilled-pepper-chicken-with-rice.jpg',
    category: 'lunch',
    calories: 460,
    protein: 54,
    carbs: 26,
    fat: 6,
    prepTime: 25,
    tags: ['high-protein', 'low-fat'],
    restaurantId: 'reflect',
    ingredients: ['Chicken breast', 'Black pepper', 'Spices', 'Rice']
  },
  {
    id: 'reflect-chicken-alfredo',
    name: 'Chicken Alfredo Pasta',
    description: 'Creamy alfredo pasta with grilled chicken',
    imageUrl: '/chicken-alfredo-pasta-creamy.jpg',
    category: 'lunch',
    calories: 440,
    protein: 50,
    carbs: 44,
    fat: 9,
    prepTime: 20,
    tags: ['high-protein'],
    restaurantId: 'reflect',
    ingredients: ['Chicken breast', 'Pasta', 'Alfredo sauce', 'Cheese']
  },
  {
    id: 'reflect-chicken-mushroom',
    name: 'Chicken With Mushroom',
    description: 'Tender chicken with creamy mushroom sauce',
    imageUrl: '/chicken-mushroom-sauce-rice.jpg',
    category: 'dinner',
    calories: 510,
    protein: 54,
    carbs: 45,
    fat: 8,
    prepTime: 30,
    tags: ['high-protein'],
    restaurantId: 'reflect',
    ingredients: ['Chicken breast', 'Mushrooms', 'Cream', 'Rice']
  },
  {
    id: 'reflect-avocado-toast',
    name: 'Avocado Toast',
    description: 'Whole grain toast topped with fresh avocado',
    imageUrl: '/avocado-toast-healthy-breakfast.jpg',
    category: 'breakfast',
    calories: 160,
    protein: 5,
    carbs: 20,
    fat: 7,
    prepTime: 10,
    tags: ['vegetarian', 'low-calorie'],
    restaurantId: 'reflect',
    ingredients: ['Whole grain bread', 'Avocado', 'Olive oil', 'Lemon']
  },
  {
    id: 'reflect-energy-toast',
    name: 'Energy Toast',
    description: 'Protein-packed toast with peanut butter and banana',
    imageUrl: '/peanut-butter-banana-toast.jpg',
    category: 'breakfast',
    calories: 350,
    protein: 12,
    carbs: 31,
    fat: 21,
    prepTime: 8,
    tags: ['high-protein'],
    restaurantId: 'reflect',
    ingredients: ['Whole grain bread', 'Peanut butter', 'Banana', 'Honey']
  },
  
  // Oz Pure meals
  {
    id: 'ozpure-sesame-salmon-bowl',
    name: 'Healthy Sesame Salmon Bowl',
    description: 'Grilled salmon with sesame seeds and vegetables',
    imageUrl: '/sesame-salmon-bowl-vegetables.jpg',
    category: 'lunch',
    calories: 607.5,
    protein: 29.5,
    carbs: 60.5,
    fat: 27.5,
    prepTime: 25,
    tags: ['high-protein'],
    restaurantId: 'oz-pure',
    ingredients: ['Salmon', 'Sesame seeds', 'Rice', 'Vegetables']
  },
  {
    id: 'ozpure-shrimp-pasta',
    name: 'Rigatoni Shrimp Pasta With Pink Sauce',
    description: 'Succulent shrimp in creamy pink sauce',
    imageUrl: '/shrimp-pasta-pink-sauce.jpg',
    category: 'dinner',
    calories: 586,
    protein: 38,
    carbs: 54.5,
    fat: 24,
    prepTime: 20,
    tags: ['high-protein'],
    restaurantId: 'oz-pure',
    ingredients: ['Shrimp', 'Rigatoni pasta', 'Pink sauce', 'Parmesan']
  },
  {
    id: 'ozpure-greek-yogurt',
    name: 'Greek Yogurt Granola',
    description: 'Protein-rich Greek yogurt with crunchy granola',
    imageUrl: '/greek-yogurt-granola-berries.jpg',
    category: 'breakfast',
    calories: 323,
    protein: 24,
    carbs: 33,
    fat: 10.5,
    prepTime: 5,
    tags: ['high-protein'],
    restaurantId: 'oz-pure',
    ingredients: ['Greek yogurt', 'Granola', 'Honey', 'Berries']
  },
  
  // Diet Market meals
  {
    id: 'dietmarket-chocolate-brownie',
    name: 'Chocolate Brownie',
    description: 'Healthy chocolate brownie with reduced sugar',
    imageUrl: '/healthy-chocolate-brownie.jpg',
    category: 'snack',
    calories: 151,
    protein: 2.1,
    carbs: 16.7,
    fat: 8.5,
    prepTime: 5,
    tags: ['low-calorie'],
    restaurantId: 'diet-market',
    ingredients: ['Whole wheat flour', 'Cocoa', 'Eggs', 'Dark chocolate']
  },
  {
    id: 'dietmarket-chicken-strips',
    name: 'Chicken Strips With Fries',
    description: 'Crispy baked chicken strips with sweet potato fries',
    imageUrl: '/baked-chicken-strips-sweet-potato-fries.jpg',
    category: 'lunch',
    calories: 481.1,
    protein: 48.9,
    carbs: 44.3,
    fat: 12.1,
    prepTime: 30,
    tags: ['high-protein'],
    restaurantId: 'diet-market',
    ingredients: ['Chicken breast', 'Sweet potato', 'Breadcrumbs', 'Spices']
  },
  {
    id: 'dietmarket-protein-pancake',
    name: 'Protein Pancake',
    description: 'Fluffy protein-enriched pancakes',
    imageUrl: '/protein-pancakes-berries.jpg',
    category: 'breakfast',
    calories: 220,
    protein: 20,
    carbs: 30,
    fat: 1.5,
    prepTime: 15,
    tags: ['high-protein', 'low-fat'],
    restaurantId: 'diet-market',
    ingredients: ['Protein powder', 'Oats', 'Eggs', 'Banana']
  },
  
  // Love Diet Food meals
  {
    id: 'lovediet-chicken-strips-fries',
    name: 'Chicken Strips with Fries',
    description: 'Crispy chicken strips with seasoned fries',
    imageUrl: '/crispy-chicken-strips-fries.jpg',
    category: 'lunch',
    calories: 217,
    protein: 22,
    carbs: 21,
    fat: 5,
    prepTime: 25,
    tags: ['high-protein', 'low-fat'],
    restaurantId: 'love-diet-food',
    ingredients: ['Chicken breast', 'Potato', 'Breadcrumbs', 'Herbs']
  },
  {
    id: 'lovediet-classic-cheese-burger',
    name: 'Classic Cheese Burger',
    description: 'Lean beef patty with cheese on whole wheat bun',
    imageUrl: '/healthy-cheese-burger-lettuce-tomato.jpg',
    category: 'lunch',
    calories: 327,
    protein: 39,
    carbs: 27,
    fat: 7,
    prepTime: 20,
    tags: ['high-protein', 'low-fat'],
    restaurantId: 'love-diet-food',
    ingredients: ['Lean beef', 'Cheese', 'Whole wheat bun', 'Lettuce', 'Tomato']
  },
  {
    id: 'lovediet-egg-shakshoka',
    name: 'Egg Shakshoka',
    description: 'Traditional poached eggs in spicy tomato sauce',
    imageUrl: '/shakshuka-eggs-tomato-sauce.jpg',
    category: 'breakfast',
    calories: 241,
    protein: 20,
    carbs: 20,
    fat: 9,
    prepTime: 20,
    tags: ['high-protein'],
    restaurantId: 'love-diet-food',
    ingredients: ['Eggs', 'Tomatoes', 'Peppers', 'Onions', 'Spices']
  },
  
  // Anabolic To Go meals
  {
    id: 'anabolic-butter-chicken',
    name: 'Butter Chicken',
    description: 'Protein-rich butter chicken with rice',
    imageUrl: '/butter-chicken-curry-rice.jpg',
    category: 'dinner',
    calories: 278,
    protein: 16.56,
    carbs: 22,
    fat: 13.96,
    prepTime: 30,
    tags: ['high-protein'],
    restaurantId: 'anabolic-to-go',
    ingredients: ['Chicken', 'Butter sauce', 'Rice', 'Spices']
  },
  {
    id: 'anabolic-super-margherita',
    name: 'Super Margarita',
    description: 'High-protein pizza with fresh mozzarella',
    imageUrl: '/placeholder.svg?height=400&width=400',
    category: 'lunch',
    calories: 598,
    protein: 31,
    carbs: 78,
    fat: 18,
    prepTime: 25,
    tags: ['high-protein'],
    restaurantId: 'anabolic-to-go',
    ingredients: ['Protein dough', 'Mozzarella', 'Tomato sauce', 'Basil']
  },
  {
    id: 'anabolic-chicken-shawarma',
    name: 'Chicken Shawarma Wrap',
    description: 'Grilled chicken with traditional spices in wrap',
    imageUrl: '/placeholder.svg?height=400&width=400',
    category: 'lunch',
    calories: 372,
    protein: 38,
    carbs: 28,
    fat: 12,
    prepTime: 15,
    tags: ['high-protein'],
    restaurantId: 'anabolic-to-go',
    ingredients: ['Chicken', 'Tortilla', 'Tahini', 'Vegetables']
  },
  
  // Crave meals
  {
    id: 'crave-kale-caesar',
    name: 'Kale Chicken Caesar Salad',
    description: 'Fresh kale with grilled chicken and Caesar dressing',
    imageUrl: '/placeholder.svg?height=400&width=400',
    category: 'lunch',
    calories: 255,
    protein: 29,
    carbs: 26,
    fat: 5,
    prepTime: 15,
    tags: ['high-protein', 'low-fat'],
    restaurantId: 'crave',
    ingredients: ['Kale', 'Chicken breast', 'Caesar dressing', 'Parmesan']
  },
  {
    id: 'crave-butter-chicken',
    name: 'Butter Chicken With White Rice',
    description: 'Classic butter chicken with fluffy white rice',
    imageUrl: '/placeholder.svg?height=400&width=400',
    category: 'dinner',
    calories: 525,
    protein: 42,
    carbs: 59,
    fat: 14,
    prepTime: 30,
    tags: ['high-protein'],
    restaurantId: 'crave',
    ingredients: ['Chicken', 'Butter sauce', 'Rice', 'Cream', 'Spices']
  },
  {
    id: 'crave-lentil-soup',
    name: 'Lentil Soup',
    description: 'Hearty and nutritious lentil soup',
    imageUrl: '/placeholder.svg?height=400&width=400',
    category: 'lunch',
    calories: 209,
    protein: 13,
    carbs: 34,
    fat: 2,
    prepTime: 40,
    tags: ['vegetarian', 'high-protein', 'low-fat'],
    restaurantId: 'crave',
    ingredients: ['Red lentils', 'Vegetables', 'Spices', 'Broth']
  },
  
  // XDiet meals
  {
    id: 'xdiet-crispy-chicken',
    name: 'Crispy Chicken',
    description: 'Baked crispy chicken with herbs',
    imageUrl: '/placeholder.svg?height=400&width=400',
    category: 'dinner',
    calories: 450,
    protein: 37,
    carbs: 48,
    fat: 9,
    prepTime: 35,
    tags: ['high-protein'],
    restaurantId: 'xdiet',
    ingredients: ['Chicken breast', 'Breadcrumbs', 'Herbs', 'Rice']
  },
  {
    id: 'xdiet-chicken-biryani',
    name: 'Chicken Baryani',
    description: 'Aromatic biryani rice with tender chicken',
    imageUrl: '/placeholder.svg?height=400&width=400',
    category: 'dinner',
    calories: 433,
    protein: 29,
    carbs: 50,
    fat: 11.5,
    prepTime: 45,
    tags: ['high-protein'],
    restaurantId: 'xdiet',
    ingredients: ['Chicken', 'Basmati rice', 'Biryani spices', 'Yogurt']
  },
  {
    id: 'xdiet-granola-yogurt',
    name: 'Granola With Yogurt',
    description: 'Homemade granola with creamy yogurt',
    imageUrl: '/placeholder.svg?height=400&width=400',
    category: 'breakfast',
    calories: 347,
    protein: 18,
    carbs: 57,
    fat: 8,
    prepTime: 5,
    tags: ['high-protein'],
    restaurantId: 'xdiet',
    ingredients: ['Granola', 'Greek yogurt', 'Honey', 'Nuts']
  },
  
  // Al Mosak meals
  {
    id: 'almosak-butter-chicken',
    name: 'Healthy Butter Chicken',
    description: 'Lighter version of classic butter chicken',
    imageUrl: '/placeholder.svg?height=400&width=400',
    category: 'dinner',
    calories: 483,
    protein: 45,
    carbs: 42,
    fat: 15,
    prepTime: 30,
    tags: ['high-protein'],
    restaurantId: 'al-mosak',
    ingredients: ['Chicken', 'Light butter sauce', 'Rice', 'Spices']
  },
  {
    id: 'almosak-chicken-katsu',
    name: 'Chicken Katsu',
    description: 'Japanese-style breaded chicken cutlet',
    imageUrl: '/placeholder.svg?height=400&width=400',
    category: 'lunch',
    calories: 347,
    protein: 29,
    carbs: 33,
    fat: 11,
    prepTime: 25,
    tags: ['high-protein'],
    restaurantId: 'al-mosak',
    ingredients: ['Chicken breast', 'Panko', 'Rice', 'Katsu sauce']
  },
  {
    id: 'almosak-shakshouka',
    name: 'Shakshouka',
    description: 'North African egg dish in spicy tomato sauce',
    imageUrl: '/placeholder.svg?height=400&width=400',
    category: 'breakfast',
    calories: 348,
    protein: 36,
    carbs: 33,
    fat: 8,
    prepTime: 25,
    tags: ['high-protein'],
    restaurantId: 'al-mosak',
    ingredients: ['Eggs', 'Tomatoes', 'Peppers', 'Onions', 'Bread']
  },
  
  // Diet House meals
  {
    id: 'diethouse-tuscan-pasta',
    name: 'Tuscan Chicken Pasta',
    description: 'Creamy Tuscan-style pasta with chicken',
    imageUrl: '/placeholder.svg?height=400&width=400',
    category: 'dinner',
    calories: 498,
    protein: 33,
    carbs: 56,
    fat: 16,
    prepTime: 25,
    tags: ['high-protein'],
    restaurantId: 'diet-house',
    ingredients: ['Chicken', 'Pasta', 'Sun-dried tomatoes', 'Spinach', 'Cream']
  },
  {
    id: 'diethouse-quinoa-tabbouleh',
    name: 'Quinoa Tabbouleh',
    description: 'Traditional tabbouleh made with quinoa',
    imageUrl: '/placeholder.svg?height=400&width=400',
    category: 'lunch',
    calories: 286,
    protein: 11,
    carbs: 43,
    fat: 15,
    prepTime: 15,
    tags: ['vegetarian'],
    restaurantId: 'diet-house',
    ingredients: ['Quinoa', 'Parsley', 'Tomatoes', 'Lemon', 'Olive oil']
  },
  {
    id: 'diethouse-avocado-egg-toast',
    name: 'Avocado & Egg on Toast',
    description: 'Whole grain toast with avocado and poached egg',
    imageUrl: '/placeholder.svg?height=400&width=400',
    category: 'breakfast',
    calories: 614,
    protein: 24,
    carbs: 54,
    fat: 34,
    prepTime: 12,
    tags: ['vegetarian', 'high-protein'],
    restaurantId: 'diet-house',
    ingredients: ['Whole grain bread', 'Avocado', 'Eggs', 'Cherry tomatoes']
  }
]

// Mock WHOOP data for onboarding (7 days)
export const whoopData: WhoopData[] = [
  {
    date: '2025-01-10',
    strain: 14.2,
    recovery: 78,
    sleepHours: 7.5,
    caloriesBurned: 2450,
    heartRateAvg: 68
  },
  {
    date: '2025-01-11',
    strain: 16.8,
    recovery: 65,
    sleepHours: 6.8,
    caloriesBurned: 2780,
    heartRateAvg: 72
  },
  {
    date: '2025-01-12',
    strain: 12.5,
    recovery: 82,
    sleepHours: 8.2,
    caloriesBurned: 2320,
    heartRateAvg: 64
  },
  {
    date: '2025-01-13',
    strain: 15.3,
    recovery: 71,
    sleepHours: 7.3,
    caloriesBurned: 2590,
    heartRateAvg: 70
  },
  {
    date: '2025-01-14',
    strain: 18.1,
    recovery: 58,
    sleepHours: 6.5,
    caloriesBurned: 2890,
    heartRateAvg: 75
  },
  {
    date: '2025-01-15',
    strain: 11.8,
    recovery: 85,
    sleepHours: 8.5,
    caloriesBurned: 2280,
    heartRateAvg: 62
  },
  {
    date: '2025-01-16',
    strain: 14.9,
    recovery: 74,
    sleepHours: 7.8,
    caloriesBurned: 2520,
    heartRateAvg: 67
  }
]
